"""Create consent_sms table.

Revision ID: 860a96ea8cf7
Revises: 198d8e99a22b
Create Date: 2025-02-03 14:41:37.447685

"""
from alembic import op
import sqlalchemy as sa
import flask_security
from flask_security.models import fsqla_v3 as fsqla
from typing import Optional


# revision identifiers, used by Alembic.
revision = '860a96ea8cf7'
down_revision = '198d8e99a22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('appVersion', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent_sms')
    # ### end Alembic commands ###
