"""empty message

Revision ID: a0e6bbf34d48
Revises: 11b4045c2dcb
Create Date: 2024-12-08 06:57:09.611135

"""
from alembic import op
import sqlalchemy as sa
import flask_security
from flask_security.models import fsqla_v3 as fsqla
from typing import Optional


# revision identifiers, used by Alembic.
revision = 'a0e6bbf34d48'
down_revision = '11b4045c2dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('appVersion', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_phone')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_confirmation_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_client', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('canceled_by_client', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('canceled_by_client')
        batch_op.drop_column('confirmed_by_client')
        batch_op.drop_column('phone_confirmed')
        batch_op.drop_column('sms_confirmation_code')

    op.drop_table('consent_sms')
    # ### end Alembic commands ###
